QUESTION1
SELECT SUBSTRING(EMAIL,1,5) FROM employees;

QUESTION 2
SELECT C.COUNTRY_NAME,count(*) FROM countries C , locations L WHERE C.COUNTRY_ID=L.COUNTRY_ID GROUP BY C.COUNTRY_NAME ORDER BY C.COUNTRY_NAME;

QUESTION 3
SELECT R.REGION_NAME,COUNT(*) FROM regions R, countries C WHERE R.REGION_ID = C.REGION_ID GROUP BY R.REGION_ID ORDER BY R.REGION_ID LIMIT 1;

QUESTION 4
SELECT EMPLOYEE_ID , FIRST_NAME,SALARY FROM employees WHERE FIRST_NAME LIKE ('j%') AND SALARY>=10000 LIMIT 1;

QUESTION 5
SELECT * FROM locations WHERE CITY LIKE '%South%';

QUESTION 6
SELECT departments.DEPARTMENT_NAME, result1.total_amt FROM departments, ( SELECT employees.DEPARTMENT_ID, SUM(employees.salary) total_amt FROM employees GROUP BY DEPARTMENT_ID) result1 WHERE result1.department_id = departments.department_id;

QUESTION 7
SELECT D.DEPARTMENT_NAME,COUNT(*) FROM departments D, employees E WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID GROUP BY D.DEPARTMENT_ID ORDER BY D.DEPARTMENT_ID;

QUESTION 8
SELECT D.DEPARTMENT_NAME,E.FIRST_NAME,E.LAST_NAME,J.EMPLOYEE_ID, MAX(DATEDIFF( IF(END_DATE='1999-12-31',CURDATE(), END_DATE) ,START_DATE)) FROM job_history J, employees E, departments D WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID AND J.EMPLOYEE_ID=E.EMPLOYEE_ID;
QUESTION 9
SELECT LAST_NAME FROM employees WHERE last_name LIKE '_____';

QUESTION 10
SELECT E.DEPARTMENT_ID,E.FIRST_NAME,E.LAST_NAME,count(*) FROM employees E , departments D WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID GROUP BY E.DEPARTMENT_ID;
